import google.genai as genai
from google.genai import types
import pandas as pd
import logging
from typing import Dict, List, Tuple

# Configure logging
logger = logging.getLogger(__name__)

# Configure Gemini API
GEMINI_API_KEY = "AIzaSyANE3N7-ZFH88WJOItlmuKZnLym-kXmKqw"

# Initialize the client
client = genai.Client(api_key=GEMINI_API_KEY)

def enhance_insights_with_llm(insights: List[str], recommendations: List[str], 
                               summary: Dict, cleaning_report: Dict = None, 
                               ml_report: Dict = None) -> str:
    """
    Enhance traditional insights using LLM to make them more comprehensive and actionable.
    Only sends summary statistics, not raw data.
    
    Args:
        insights: List of traditional insights
        recommendations: List of traditional recommendations
        summary: Dataset summary dictionary
        cleaning_report: Report from auto_clean() (optional)
        ml_report: Machine learning evaluation report (optional)
    
    Returns:
        str: Enhanced insights and recommendations
    """
    try:
        # Build a concise summary (to minimize tokens)
        dataset_summary = f"""
Dataset Shape: {summary['shape'][0]} rows, {summary['shape'][1]} columns
Missing Values: {sum(summary['missing_values'].values())} total
Duplicates: {summary['duplicates']}
"""

        # Add cleaning info if available
        cleaning_summary = ""
        if cleaning_report:
            cleaning_summary = f"""
Cleaning Applied:
- Handled missing values in {len(cleaning_report.get('missing_handled', {}))} columns
- Removed {cleaning_report.get('duplicates_removed', 0)} duplicates
- Capped outliers in {len(cleaning_report.get('outliers_capped', {}))} columns
"""

        # Add ML info if available
        ml_summary = ""
        if ml_report:
            if isinstance(ml_report, dict):
                if 'accuracy' in str(ml_report).lower() or 'f1' in str(ml_report).lower():
                    ml_summary = "\nMachine Learning: Classification model trained"
                    if 'Cross_Validation_Score' in ml_report:
                        ml_summary += f" (CV Score: {ml_report['Cross_Validation_Score']:.2f})"
                elif 'R² Score' in ml_report:
                    ml_summary = f"\nMachine Learning: Regression model trained (R² Score: {ml_report['R² Score']:.2f})"

        # Combine traditional insights
        traditional_insights_text = "\n".join([f"- {insight}" for insight in insights])
        traditional_recommendations_text = "\n".join([f"- {rec}" for rec in recommendations])

        # Create a concise prompt
        prompt = f"""You are a data analysis expert. Transform the following analysis into a comprehensive, professional report.

{dataset_summary}
{cleaning_summary}
{ml_summary}

CURRENT INSIGHTS:
{traditional_insights_text}

CURRENT RECOMMENDATIONS:
{traditional_recommendations_text}

YOUR TASK:
Create a well-structured, professional analysis report with these sections:

## 📊 Dataset Overview
Summarize the key characteristics and data quality.

## 🔍 Key Findings
Expand on the insights with deeper explanations and implications.

## 💡 Statistical Patterns
Explain the statistical patterns discovered and what they mean.

## ⚠️ Data Quality Assessment
Discuss data quality, cleaning performed, and any remaining concerns.

## 🎯 Strategic Recommendations
Provide specific, actionable next steps for:
- Further analysis
- Feature engineering
- Model improvement (if applicable)
- Data collection improvements

## 📈 Business Impact
Explain what these findings mean in practical terms and potential business value.

Requirements:
- Be specific with numbers and percentages
- Make insights actionable and clear
- Use professional but accessible language
- Focus on practical implications
- Keep it concise but comprehensive (aim for 500-800 words)
- Use emojis for visual appeal
- Do NOT mention that you are an AI or that this was generated by AI
"""

        # Generate enhanced insights using new API
        logger.info("Enhancing insights with LLM...")
        
        response = client.models.generate_content(
            model='gemini-2.0-flash-exp',
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.7,
                top_p=0.8,
                top_k=40,
                max_output_tokens=2048,
            )
        )
        
        enhanced_insights = response.text
        logger.info("Insights enhanced successfully")
        
        return enhanced_insights
        
    except Exception as e:
        logger.error(f"Error enhancing insights with LLM: {str(e)}")
        # Fallback to traditional insights if LLM fails
        fallback = f"""## 📊 Dataset Overview

{dataset_summary}

## 🔍 Key Findings

{traditional_insights_text}

## 🎯 Recommendations

{traditional_recommendations_text}

---
*Note: Enhanced analysis temporarily unavailable. Showing traditional insights.*
"""
        return fallback


def generate_quick_summary(summary: Dict, insights: List[str], recommendations: List[str]) -> str:
    """
    Generate a quick summary without using LLM (fallback option).
    
    Args:
        summary: Dataset summary dictionary
        insights: List of insights
        recommendations: List of recommendations
    
    Returns:
        str: Quick formatted summary
    """
    try:
        output = f"""## 📊 Dataset Summary

**Size:** {summary['shape'][0]} rows × {summary['shape'][1]} columns
**Missing Values:** {sum(summary['missing_values'].values())} total
**Duplicate Rows:** {summary['duplicates']}

## 🔍 Key Insights

"""
        for i, insight in enumerate(insights, 1):
            output += f"{i}. {insight}\n"
        
        output += "\n## 🎯 Recommendations\n\n"
        for i, rec in enumerate(recommendations, 1):
            output += f"{i}. {rec}\n"
        
        return output
        
    except Exception as e:
        logger.error(f"Error generating quick summary: {str(e)}")
        return "Error generating summary. Please try again."